name: Update en.json from system

on:
  schedule:
    - cron: '0 0 * * *' # Se déclenche tous les jours à minuit (UTC)
  workflow_dispatch: # Permet de déclencher manuellement l'action


jobs:
  update-en-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref_name }}

    - name: Download en.json from foundryvtt/dnd5e
      run: curl -o en.json https://raw.githubusercontent.com/foundryvtt/dnd5e/4.0.x/lang/en.json

    - name: Download packs/_source from foundryvtt/dnd5e
      run: |
        mkdir -p en/packs/_source
        wget -r -np -nH --cut-dirs=3 -P packs/_source --reject "index.html*" https://github.com/foundryvtt/dnd5e/raw/4.0.x/packs/_source/

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        if [ -n "$(git status --porcelain)" ]; then
          git add en.json en/packs/_source
          git commit -m "Update en.json and packs/_source from foundryvtt/dnd5e"
          git push origin ${{ github.ref_name }}
        else
          echo "No changes to commit"
        fi
